plugins: cmake
canonical/craft-parts pull request #184
Opened 2022-03-16 15:05 UTC by mr-cal

- [X] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

Port `cmake` plugin to `craft-parts`.

(CRAFT-906)

2022-03-16 16:23 UTC, cmatsuoka requested changes

2022-03-16 16:23 UTC, cmatsuoka commented on tests/integration/plugins/test_cmake.py
> +    subprocess.run(["pip", "uninstall", "cmake", "--yes"], check=True)
This is an interesting way to install cmake, but I think it's better to just install it from the archive when preparing the CI environment in the [github workflow](https://github.com/canonical/craft-parts/blob/7aa01bd45fb8652a09484f46ee77278f03a50f50/.github/workflows/tests.yaml#L82).

2022-03-16 16:23 UTC, cmatsuoka commented on tests/integration/plugins/test_cmake.py
> +@pytest.mark.usefixtures("mocker")
Is this necessary? I don't think we can use the mocker fixture this way.

2022-03-16 16:23 UTC, cmatsuoka commented on tests/integration/plugins/test_cmake.py
> +    # ninja is installed in the ci test setup
This should be cmake, if we install it in the ci setup.

2022-03-16 16:23 UTC, cmatsuoka commented on craft_parts/plugins/cmake_plugin.py
> +# Copyright 2020 Canonical Ltd.
Since we're porting this to craft-parts we should use 2020-2022 in the copyright notice.

2022-03-16 16:23 UTC, cmatsuoka commented on tests/integration/plugins/test_cmake.py
> +@pytest.mark.usefixtures("cmake")
This should also be unnecessary if we install cmake in the ci setup.

2022-03-16 17:16 UTC, mr-cal commented
Thanks for the thorough review, there was more cruft leftover than I realized.

2022-03-17 02:32 UTC, sergiusens commented on craft_parts/plugins/cmake_plugin.py
> +        - SNAPCRAFT_CMAKE_ARGS
I would remove this fow now, we used this from the extension for kde but it shouldbe solved some other way

2022-03-17 02:32 UTC, sergiusens commented on craft_parts/plugins/cmake_plugin.py
> +        - SNAPCRAFT_CMAKE_ARGS
we can re-add later if creativity does not allow for us to get there :-)

2022-03-17 19:19 UTC, sergiusens approved these changes
we don't seem to be using environment validation here, for perhaps to account for someone wanting to use a newer cmake but this is a good start.

2022-03-17 19:35 UTC, cmatsuoka approved these changes
Thanks Callahan!

2022-03-17 19:39 UTC, merged