chore: move partitions to top-level directory
canonical/craft-parts pull request #627
Opened 2024-01-23 00:48 UTC by mr-cal

- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

Move partitions to top-level directory.

Fixes #620
(CRAFT-2389)

2024-01-23 15:21 UTC, mr-cal commented
Test failures unrelated, see https://github.com/canonical/craft-parts/pull/628

2024-01-24 18:19 UTC, cmatsuoka commented on craft_parts/executor/organize.py
> +                "install",
This could share a helper with the ProjectDirs initialization instead of redefining the path building rule.

2024-01-24 18:19 UTC, cmatsuoka commented on craft_parts/executor/step_handler.py
> +        if self._partitions:
If using the `for_each_partition` idea this could be handled in a uniform way without exposed conditionals.

2024-01-25 14:46 UTC, mr-cal commented on craft_parts/dirs.py
> +            self.partition_dir: Optional[Path] = self.work_dir / "partitions"
Good catch!

2024-01-25 14:53 UTC, mr-cal commented on craft_parts/sources/local_source.py
> +                self._ignore_patterns.append(self._dirs.partition_dir.name)
https://github.com/canonical/craft-parts/issues/636

2024-01-25 14:57 UTC, mr-cal commented on craft_parts/parts.py
> +            )
Is that possible?  Install dirs are per-part and `ProjectDirs` isn't aware of any part names.

2024-01-25 21:07 UTC, lengau requested changes

2024-01-26 20:30 UTC, cmatsuoka approved these changes
Overall it seems good, considering that we already have some refactoring planned. I think we can move forward and address those in a future PR.

2024-01-26 20:30 UTC, cmatsuoka commented on craft_parts/parts.py
> +            )
Good point. We could still move it to the part initialization or use a cached result so we won't recompute it every time. Can be done in a refactoring round.

2024-01-26 20:30 UTC, cmatsuoka commented on craft_parts/executor/organize.py
> +                "install",
Or part initialization, as you mentioned before.

2024-01-29 14:50 UTC, mr-cal commented on craft_parts/executor/filesets.py
> +            if split_file[1] == "*":
Ah yes, thanks!

2024-01-29 14:50 UTC, mr-cal commented on craft_parts/executor/collisions.py
Done!

2024-01-29 14:54 UTC, mr-cal commented on tests/unit/executor/test_filesets.py
>  def test_fileset_only_includes():
Check out `tests/unit/features/partitions/executor/test_filesets.py`, I think these are covered.

To be fair, `tests/unit/executor/test_filesets.py` does a better job of separating different scenarios into their own tests.  I'll work on migrating these tests to `tests/unit/features/partitions/executor/test_filesets.py`.

2024-01-29 14:54 UTC, mr-cal commented on tests/unit/executor/test_step_handler.py
> +                    itertools.chain.from_iterable(
Thanks

2024-01-29 14:55 UTC, mr-cal commented on tests/unit/features/partitions/executor/test_organize.py
>  @pytest.mark.parametrize(
Done, this removed a fair amount of boilerplate.

2024-01-29 14:56 UTC, mr-cal commented on tests/unit/features/partitions/test_dirs.py
> +        },
Great suggestion.  This made the code much cleaner.  I was able to use it everywhere except `craft_parts/executor/organize.py`, which has a subtle and fragile use of relative directories.

2024-01-29 20:28 UTC, mr-cal commented
Ready for re-review.  `Fileset.combine()`  is not partition aware, so I marked its tests with `xfail`.  This PR is getting too big, so I want to fix it in another PR.

2024-01-29 20:34 UTC, mr-cal commented
Linter failure unrelated, resolved in #638

2024-01-30 17:40 UTC, lengau approved these changes
Great work!

2024-01-31 15:36 UTC, merged