fix(sequencer): rerun steps only if explicitly requested
canonical/craft-parts pull request #727
Opened 2024-05-15 13:50 UTC by cmatsuoka

Instead of implicitly cleaning and re-executing steps when a part name
is specified, only do it when explicitly requested by the user.
Applications must set the `rerun` argument accordingly when planning
the lifecycle execution.

- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

2024-05-16 13:48 UTC, mr-cal requested changes
Looks good!

Can you add/extend an integration test in `tests/integration/sequencer/test_sequencer.py`?

2024-05-27 21:12 UTC, cmatsuoka commented
Rebased on feature/2.0

2024-05-31 18:58 UTC, lengau approved these changes

2024-05-31 18:58 UTC, merged

2024-08-06 12:45 UTC, kubiko commented
@cmatsuoka @mr-cal @tigarmo 
Is still suppose to fix when `snapcraft build <part>` does clean step? Because it does not seem to work