license: change the license to LGPLv3 (CRAFT-328)
canonical/craft-parts pull request #88
Opened 2021-06-28 18:37 UTC by cmatsuoka

Change craft-parts license to LGPLv3 so it can be used as a library by
non-GPL applications.

Signed-off-by: Claudio Matsuoka <claudio.matsuoka@canonical.com>

- [x] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?

-----

2021-06-28 19:37 UTC, sergiusens approved these changes

2021-06-29 12:40 UTC, facundobatista approved these changes
+1

2021-06-29 12:53 UTC, cjp256 requested changes
Don't forget to update `license` in setup.py: https://github.com/canonical/craft-parts/blob/7521b225710ff07712d2b9e1fef9b93304953492/setup.py#L55

2021-06-29 13:46 UTC, cjp256 approved these changes

2021-06-29 14:09 UTC, merged