docs: update and complete the step execution environment
canonical/craft-parts pull request #949
Opened 2024-12-20 00:53 UTC by lengau

This adds a large number of missing environment variables from the step execution environment and updates the information about CRAFT_TARGET_ARCH and CRAFT_ARCH_TRIPLET being deprecated.

- [ ] Have you signed the [CLA](http://www.ubuntu.com/legal/contributors/)?
- [ ] Have you added an entry to the changelog (`docs/reference/changelog.rst`)?

-----

2025-01-21 22:02 UTC, mr-cal approved these changes
Looks good!

2025-01-21 22:02 UTC, mr-cal commented on docs/common/craft-parts/reference/step_execution_environment.rst
> +``PATH`` if they exist. These paths are:
Think there is any value in mentioning the order for this and the sections below?

```suggestion
``PATH`` if they exist. These paths are, in order:
```

2025-01-24 13:44 UTC, mr-cal commented on docs/common/craft-parts/reference/step_execution_environment.rst
> +    - The architecture triplet of the build target. For example:
```suggestion
    - The architecture of the build target. For example:
```

2025-01-24 13:44 UTC, mr-cal commented on docs/common/craft-parts/reference/step_execution_environment.rst
> +    - The architecture triplet of the build target. For example:
```suggestion
    - The architecture of the build target. For example:
```

2025-01-24 16:44 UTC, lengau commented on docs/common/craft-parts/reference/step_execution_environment.rst
> +    - The architecture triplet of the build target. For example:
Good catch, thanks!

2025-01-24 18:59 UTC, jahn-junior requested changes
Other than the one small request, everything looks good!

2025-01-24 18:59 UTC, jahn-junior commented on docs/common/craft-parts/reference/step_execution_environment.rst
> +Each of these variables is set with a series of ``-isystem`` parameters added
```suggestion
Each of these variables is set with a series of ``-isystem`` parameters
```

2025-01-24 19:11 UTC, jahn-junior approved these changes

2025-01-27 16:07 UTC, merged